"""passageiro sem vaga (viagem_dia_id nulo)

Revision ID: 00e41e6a5bd5
Revises: f0b268151c26
Create Date: 2026-07-11 12:27:31.813725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e41e6a5bd5'
down_revision: Union[str, Sequence[str], None] = 'f0b268151c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagem_dia_passageiro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.Date(), nullable=True))
        batch_op.alter_column('viagem_dia_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagem_dia_passageiro', schema=None) as batch_op:
        batch_op.alter_column('viagem_dia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('data')

    # ### end Alembic commands ###
