"""adiciona periodo em condutor

Revision ID: 1226615e3de8
Revises: be21fee2c00a
Create Date: 2026-07-09 16:44:08.032987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1226615e3de8'
down_revision: Union[str, Sequence[str], None] = 'be21fee2c00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodo', sa.Enum('MANHA', 'TARDE', name='periodocondutor', native_enum=False, length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condutor', schema=None) as batch_op:
        batch_op.drop_column('periodo')

    # ### end Alembic commands ###
