"""remove agendamento base, add capacidade em veiculo e ordem em agenda semanal

Revision ID: 613ace416f4b
Revises: 98ba361c9edc
Create Date: 2026-07-10 11:47:07.960343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613ace416f4b'
down_revision: Union[str, Sequence[str], None] = '98ba361c9edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # a FK de viagem_dia para agendamento_base precisa cair antes de dropar a
    # tabela agendamento_base, senao o batch mode do sqlite falha ao tentar
    # refletir essa FK durante a recriacao da tabela.
    with op.batch_alter_table('viagem_dia', schema=None) as batch_op:
        batch_op.drop_column('agendamento_base_id')

    op.drop_table('usuario_agendamento_base')
    op.drop_table('agendamento_base')
    with op.batch_alter_table('usuario_agenda_semanal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordem', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidade', sa.Integer(), nullable=False, server_default='4'))
        batch_op.create_check_constraint('ck_veiculo_capacidade', 'capacidade > 0')

    with op.batch_alter_table('usuario_agenda_semanal', schema=None) as batch_op:
        batch_op.alter_column('ordem', server_default=None)

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.alter_column('capacidade', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # agendamento_base precisa existir antes de recriar a FK em viagem_dia
    # apontando para ela.
    op.create_table('agendamento_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dia_tipo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('regiao_id', sa.INTEGER(), nullable=False),
    sa.Column('inicio', sa.TIME(), nullable=False),
    sa.Column('capacidade', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('capacidade > 0', name=op.f('ck_agendamento_base_capacidade')),
    sa.ForeignKeyConstraint(['regiao_id'], ['regiao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_agendamento_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agendamento_base_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('sentido', sa.VARCHAR(length=20), nullable=False),
    sa.Column('hora', sa.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['agendamento_base_id'], ['agendamento_base.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agendamento_base_id', 'usuario_id', 'sentido', name=op.f('uq_usuario_agendamento_base'))
    )

    with op.batch_alter_table('viagem_dia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agendamento_base_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'agendamento_base', ['agendamento_base_id'], ['id'])

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_column('capacidade')

    with op.batch_alter_table('usuario_agenda_semanal', schema=None) as batch_op:
        batch_op.drop_column('ordem')

    # ### end Alembic commands ###
