"""indices para viagem_dia.data, frequencia.data, usuario_agenda_semanal.dia_semana e condutor_ferias periodo

Revision ID: 6b9c405e0d6c
Revises: 00e41e6a5bd5
Create Date: 2026-07-11 14:14:27.581838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9c405e0d6c'
down_revision: Union[str, Sequence[str], None] = '00e41e6a5bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condutor_ferias', schema=None) as batch_op:
        batch_op.create_index('ix_condutor_ferias_periodo', ['data_inicio', 'data_fim'], unique=False)

    with op.batch_alter_table('frequencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frequencia_data'), ['data'], unique=False)

    with op.batch_alter_table('usuario_agenda_semanal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_agenda_semanal_dia_semana'), ['dia_semana'], unique=False)

    with op.batch_alter_table('viagem_dia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viagem_dia_data'), ['data'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagem_dia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viagem_dia_data'))

    with op.batch_alter_table('usuario_agenda_semanal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_agenda_semanal_dia_semana'))

    with op.batch_alter_table('frequencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frequencia_data'))

    with op.batch_alter_table('condutor_ferias', schema=None) as batch_op:
        batch_op.drop_index('ix_condutor_ferias_periodo')

    # ### end Alembic commands ###
