"""tabela conta (login/permissao)

Revision ID: 895ce65ae638
Revises: 6b9c405e0d6c
Create Date: 2026-07-11 14:36:45.297656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895ce65ae638'
down_revision: Union[str, Sequence[str], None] = '6b9c405e0d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=100), nullable=False),
    sa.Column('papel', sa.Enum('ADMIN', 'OPERADOR', name='papelconta', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statusativoinativo', native_enum=False, length=20), nullable=False),
    sa.Column('criado_em', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta')
    # ### end Alembic commands ###
