"""adiciona modalidade e acompanhante em usuario_agenda_semanal

Revision ID: 98ba361c9edc
Revises: 1226615e3de8
Create Date: 2026-07-10 09:47:01.582747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ba361c9edc'
down_revision: Union[str, Sequence[str], None] = '1226615e3de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_agenda_semanal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modalidade', sa.Enum('SOMENTE_IDA', 'IDA_E_VOLTA', name='modalidade', native_enum=False, length=20), nullable=False, server_default='IDA_E_VOLTA'))
        batch_op.add_column(sa.Column('acompanhante', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('usuario_agenda_semanal', schema=None) as batch_op:
        batch_op.alter_column('modalidade', server_default=None)
        batch_op.alter_column('acompanhante', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_agenda_semanal', schema=None) as batch_op:
        batch_op.drop_column('acompanhante')
        batch_op.drop_column('modalidade')

    # ### end Alembic commands ###
