"""adiciona equoterapia em tipolocal

Revision ID: be21fee2c00a
Revises: e3fae2656972
Create Date: 2026-07-09 15:37:17.782396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be21fee2c00a'
down_revision: Union[str, Sequence[str], None] = 'e3fae2656972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
