"""adiciona observacao em local

Revision ID: e3fae2656972
Revises: f77c08918a4d
Create Date: 2026-07-07 15:48:17.607877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fae2656972'
down_revision: Union[str, Sequence[str], None] = 'f77c08918a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local', schema=None) as batch_op:
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###
