"""add acompanhante em usuario_excecao

Revision ID: ece1ffd29ff4
Revises: c853200700dc
Create Date: 2026-07-13 20:56:24.397550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece1ffd29ff4'
down_revision: Union[str, Sequence[str], None] = 'c853200700dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_excecao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acompanhante', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_excecao', schema=None) as batch_op:
        batch_op.drop_column('acompanhante')

    # ### end Alembic commands ###
