"""local recesso

Revision ID: f0b268151c26
Revises: 43bea91eeacc
Create Date: 2026-07-11 10:40:05.864679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b268151c26'
down_revision: Union[str, Sequence[str], None] = '43bea91eeacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_recesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.CheckConstraint('data_fim >= data_inicio', name='ck_local_recesso_periodo'),
    sa.ForeignKeyConstraint(['local_id'], ['local.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('local_recesso')
    # ### end Alembic commands ###
