"""schema inicial

Revision ID: f77c08918a4d
Revises: 
Create Date: 2026-07-07 08:37:46.635402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77c08918a4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('regiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('abbr', sa.String(length=30), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statusativoinativo', native_enum=False, length=20), nullable=False),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_tipo', sa.Enum('UTIL', 'SABADO', 'DOMINGO', name='diatipo', native_enum=False, length=20), nullable=False),
    sa.Column('regiao_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Time(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.CheckConstraint('capacidade > 0', name='ck_agendamento_base_capacidade'),
    sa.ForeignKeyConstraint(['regiao_id'], ['regiao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_regiao',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('regiao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['regiao_id'], ['regiao.id'], ),
    sa.PrimaryKeyConstraint('empresa_id', 'regiao_id')
    )
    op.create_table('local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('ESCOLA', 'FISIOTERAPIA', 'TRABALHO', 'HEMODIALISE', 'OUTROS', name='tipolocal', native_enum=False, length=20), nullable=False),
    sa.Column('regiao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regiao_id'], ['regiao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('prefixo', sa.String(length=20), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'MANUTENCAO', name='statusveiculo', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('condutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('apelido', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'DESLIGADO', 'AFASTADO', name='statuscondutor', native_enum=False, length=20), nullable=False),
    sa.Column('veiculo_preferencial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['veiculo_preferencial_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('usuario_agenda_semanal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB', 'DOM', name='diasemana', native_enum=False, length=20), nullable=False),
    sa.Column('tipo', sa.Enum('FIXO', 'EVENTUAL', name='tipoatendimento', native_enum=False, length=20), nullable=False),
    sa.Column('saida', sa.Time(), nullable=True),
    sa.Column('retorno', sa.Time(), nullable=True),
    sa.Column('origem', sa.String(length=200), nullable=True),
    sa.Column('regiao_origem_id', sa.Integer(), nullable=True),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['destino_id'], ['local.id'], ),
    sa.ForeignKeyConstraint(['regiao_origem_id'], ['regiao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'dia_semana', name='uq_usuario_dia_semana')
    )
    op.create_table('usuario_agendamento_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_base_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sentido', sa.Enum('IDA', 'RETORNO', name='sentido', native_enum=False, length=20), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['agendamento_base_id'], ['agendamento_base.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agendamento_base_id', 'usuario_id', 'sentido', name='uq_usuario_agendamento_base')
    )
    op.create_table('usuario_excecao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('suspenso', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.Enum('FIXO', 'EVENTUAL', name='tipoatendimento', native_enum=False, length=20), nullable=True),
    sa.Column('saida', sa.Time(), nullable=True),
    sa.Column('retorno', sa.Time(), nullable=True),
    sa.Column('origem', sa.String(length=200), nullable=True),
    sa.Column('regiao_origem_id', sa.Integer(), nullable=True),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['destino_id'], ['local.id'], ),
    sa.ForeignKeyConstraint(['regiao_origem_id'], ['regiao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'data', name='uq_usuario_excecao_data')
    )
    op.create_table('condutor_ferias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condutor_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.CheckConstraint('data_fim >= data_inicio', name='ck_condutor_ferias_periodo'),
    sa.ForeignKeyConstraint(['condutor_id'], ['condutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frequencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condutor_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('TRABALHADO', 'FOLGA', 'FERIAS', 'FALTA', 'PENDENTE', name='statusfrequencia', native_enum=False, length=20), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=True),
    sa.Column('intervalo_inicio', sa.Time(), nullable=True),
    sa.Column('intervalo_fim', sa.Time(), nullable=True),
    sa.Column('hora_saida', sa.Time(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['condutor_id'], ['condutor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condutor_id', 'data', name='uq_frequencia_condutor_data')
    )
    op.create_table('viagem_dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('agendamento_base_id', sa.Integer(), nullable=True),
    sa.Column('regiao_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('condutor_id', sa.Integer(), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('horario_saida', sa.Time(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANEJADA', 'CONFIRMADA', 'CANCELADA', name='statusviagemdia', native_enum=False, length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.CheckConstraint('capacidade > 0', name='ck_viagem_dia_capacidade'),
    sa.ForeignKeyConstraint(['agendamento_base_id'], ['agendamento_base.id'], ),
    sa.ForeignKeyConstraint(['condutor_id'], ['condutor.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['regiao_id'], ['regiao.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viagem_dia_passageiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viagem_dia_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sentido', sa.Enum('IDA', 'RETORNO', name='sentido', native_enum=False, length=20), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('origem', sa.String(length=200), nullable=True),
    sa.Column('regiao_origem_id', sa.Integer(), nullable=True),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('regiao_destino_id', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AGENDADO', 'CANCELADO', 'EM_ANALISE', name='statusatendimentodia', native_enum=False, length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['destino_id'], ['local.id'], ),
    sa.ForeignKeyConstraint(['regiao_destino_id'], ['regiao.id'], ),
    sa.ForeignKeyConstraint(['regiao_origem_id'], ['regiao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['viagem_dia_id'], ['viagem_dia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viagem_dia_id', 'usuario_id', 'sentido', name='uq_viagem_dia_passageiro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viagem_dia_passageiro')
    op.drop_table('viagem_dia')
    op.drop_table('frequencia')
    op.drop_table('condutor_ferias')
    op.drop_table('usuario_excecao')
    op.drop_table('usuario_agendamento_base')
    op.drop_table('usuario_agenda_semanal')
    op.drop_table('condutor')
    op.drop_table('veiculo')
    op.drop_table('local')
    op.drop_table('empresa_regiao')
    op.drop_table('agendamento_base')
    op.drop_table('usuario')
    op.drop_table('regiao')
    op.drop_table('empresa')
    # ### end Alembic commands ###
